# ==================================================
# CONFIGURATION GLOBALE DU SYSTÈME D'ORIENTATION
# ==================================================

# Chemins (relatifs à la racine du projet backend_ml)
paths:
  data: "data"
  data_raw: "data/raw"
  data_processed: "data/processed"
  data_synthetic: "data/synthetic"
  models_saved: "models/saved"
  rules: "models/rules"
  logs: "logs"

# Fichiers
files:
  generated_data: "generated_data.csv"
  rules: "orientation_rules.json"
  model: "orientation_model.pkl"
  scaler: "scaler.pkl"
  encoder: "label_encoder.pkl"

# Modèle ML
model:
  type: "RandomForest"
  test_size: 0.2
  random_state: 42
  rf_params:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 5
    min_samples_leaf: 2

# Pondération du système hybride
weights:
  rules: 0.4
  ml: 0.6