# =================================================
# CONFIGURATION GLOBALE DU SYSTÈME D'ORIENTATION
# =================================================

# --- Chemins et Fichiers ---
paths:
  data_raw: "data/raw/"
  data_processed: "data/processed/"
  data_synthetic: "data/synthetic/"
  models_saved: "models/saved/"
  rules: "models/rules/"
  logs: "logs/"

files:
  synthetic_data: "generated_data.csv"
  rules: "orientation_rules.json"
  model: "orientation_model.pkl"
  scaler: "scaler.pkl"
  encoder: "label_encoder.pkl"

# --- Filières ---
# Liste complète des filières gérées par le système
filieres:
  - "Génie Logiciel"
  - "Intelligence Artificielle"
  - "Big Data"
  - "Objets Connectés (IoT)"
  - "Cybersécurité"
  - "Robotique"
  - "Aéronautique"
  - "Pilotage"
  - "Pétrochimie"
  - "Topographie"
  - "Maintenance Automobile"

# --- Modèle ML ---
model:
  algorithm: "RandomForest"
  test_size: 0.2
  random_state: 42
  rf_params:
    n_estimators: 100
    max_depth: 15
    min_samples_leaf: 2

# --- Système Hybride ---
weights:
  rules: 0.4
  ml: 0.6