"""Initial migration complete

Revision ID: a02e91ae920e
Revises: 
Create Date: 2026-04-28 20:33:59.521988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02e91ae920e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facultes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=155), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facultes_id'), 'facultes', ['id'], unique=False)
    op.create_index(op.f('ix_facultes_nom'), 'facultes', ['nom'], unique=False)
    op.create_table('semesters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semesters_id'), 'semesters', ['id'], unique=False)
    op.create_table('departements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=155), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id_faculte', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_faculte'], ['facultes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departements_id'), 'departements', ['id'], unique=False)
    op.create_index(op.f('ix_departements_nom'), 'departements', ['nom'], unique=False)
    op.create_table('parcours',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('niveau', sa.String(length=255), nullable=False),
    sa.Column('duree', sa.Integer(), nullable=False),
    sa.Column('id_departement', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_departement'], ['departements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcours_duree'), 'parcours', ['duree'], unique=False)
    op.create_index(op.f('ix_parcours_id'), 'parcours', ['id'], unique=False)
    op.create_index(op.f('ix_parcours_niveau'), 'parcours', ['niveau'], unique=False)
    op.create_index(op.f('ix_parcours_nom'), 'parcours', ['nom'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_teacher', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('id_departement', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['id_departement'], ['departements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=False)
    op.create_index(op.f('ix_teachers_grade'), 'teachers', ['grade'], unique=False)
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_id_teacher'), 'teachers', ['id_teacher'], unique=True)
    op.create_index(op.f('ix_teachers_nom'), 'teachers', ['nom'], unique=False)
    op.create_index(op.f('ix_teachers_prenom'), 'teachers', ['prenom'], unique=False)
    op.create_index(op.f('ix_teachers_telephone'), 'teachers', ['telephone'], unique=False)
    op.create_table('cours',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=155), nullable=False),
    sa.Column('titre', sa.String(length=155), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('id_parcours', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_parcours'], ['parcours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cours_code'), 'cours', ['code'], unique=False)
    op.create_index(op.f('ix_cours_credits'), 'cours', ['credits'], unique=False)
    op.create_index(op.f('ix_cours_id'), 'cours', ['id'], unique=False)
    op.create_index(op.f('ix_cours_titre'), 'cours', ['titre'], unique=False)
    op.create_table('etudiants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_etudiant', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=False),
    sa.Column('lieu_naissance', sa.String(length=100), nullable=False),
    sa.Column('sexe', sa.String(length=10), nullable=False),
    sa.Column('nationalite', sa.String(length=50), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('nom_du_pere', sa.String(length=100), nullable=False),
    sa.Column('nom_de_la_mere', sa.String(length=100), nullable=False),
    sa.Column('addresse_du_pere', sa.String(length=100), nullable=False),
    sa.Column('addresse_de_la_mere', sa.String(length=100), nullable=False),
    sa.Column('nom_parent_tuteur', sa.String(length=100), nullable=False),
    sa.Column('telephone_parent_tuteur', sa.String(length=20), nullable=False),
    sa.Column('adresse_parent_tuteur', sa.String(length=255), nullable=False),
    sa.Column('date_inscription', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_departement', sa.String(length=36), nullable=True),
    sa.Column('id_parcours', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['id_departement'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['id_parcours'], ['parcours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etudiants_date_naissance'), 'etudiants', ['date_naissance'], unique=False)
    op.create_index(op.f('ix_etudiants_email'), 'etudiants', ['email'], unique=True)
    op.create_index(op.f('ix_etudiants_id'), 'etudiants', ['id'], unique=False)
    op.create_index(op.f('ix_etudiants_id_etudiant'), 'etudiants', ['id_etudiant'], unique=True)
    op.create_index(op.f('ix_etudiants_lieu_naissance'), 'etudiants', ['lieu_naissance'], unique=False)
    op.create_index(op.f('ix_etudiants_nom'), 'etudiants', ['nom'], unique=False)
    op.create_index(op.f('ix_etudiants_prenom'), 'etudiants', ['prenom'], unique=False)
    op.create_index(op.f('ix_etudiants_sexe'), 'etudiants', ['sexe'], unique=False)
    op.create_table('enrollment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('semester_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['etudiants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_id'), 'enrollment', ['id'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('semester_id', sa.String(length=36), nullable=True),
    sa.Column('grade_value', sa.Float(), nullable=False),
    sa.Column('grade_type', sa.String(length=50), nullable=False),
    sa.Column('date_assigned', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['etudiants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('is_principal', sa.Boolean(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('encryption_key_id', sa.String(length=50), nullable=True),
    sa.Column('checksum', sa.String(length=50), nullable=True),
    sa.Column('storage_location', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['etudiants.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_table('teach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teach_id'), 'teach', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['etudiants.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_hashed_password'), 'users', ['hashed_password'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_superuser'), 'users', ['is_superuser'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_index(op.f('ix_tokens_token'), 'tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_token'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_superuser'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_hashed_password'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teach_id'), table_name='teach')
    op.drop_table('teach')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_enrollment_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_etudiants_sexe'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_prenom'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_nom'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_lieu_naissance'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_id_etudiant'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_id'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_email'), table_name='etudiants')
    op.drop_index(op.f('ix_etudiants_date_naissance'), table_name='etudiants')
    op.drop_table('etudiants')
    op.drop_index(op.f('ix_cours_titre'), table_name='cours')
    op.drop_index(op.f('ix_cours_id'), table_name='cours')
    op.drop_index(op.f('ix_cours_credits'), table_name='cours')
    op.drop_index(op.f('ix_cours_code'), table_name='cours')
    op.drop_table('cours')
    op.drop_index(op.f('ix_teachers_telephone'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_prenom'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_nom'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id_teacher'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_grade'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_parcours_nom'), table_name='parcours')
    op.drop_index(op.f('ix_parcours_niveau'), table_name='parcours')
    op.drop_index(op.f('ix_parcours_id'), table_name='parcours')
    op.drop_index(op.f('ix_parcours_duree'), table_name='parcours')
    op.drop_table('parcours')
    op.drop_index(op.f('ix_departements_nom'), table_name='departements')
    op.drop_index(op.f('ix_departements_id'), table_name='departements')
    op.drop_table('departements')
    op.drop_index(op.f('ix_semesters_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_facultes_nom'), table_name='facultes')
    op.drop_index(op.f('ix_facultes_id'), table_name='facultes')
    op.drop_table('facultes')
    # ### end Alembic commands ###
